train: True # change
batch_size: 64 # change
epochs: 30
eval_every_n_epochs: 2
log_every_n_steps: 200
learning_rate: 4e-4 # change 8e-4
weight_decay: 1e-6
dset: shapenet
CLIP: False
info: "../data/snare/amt/processed_json/info.json"
log_dir: None
expr_id: None

model:
  out_dim: 512
  sparse_model: False
  use_voxel: False
  tri_modal: False
  num_images: 8
  image_cnn: 'resnet18'
  pretraining: True
  vocab_size: 6568

dataset:
  num_workers: 4 # change
  train_json_file: "../data/snare/amt/processed_json/processed_train.json"
  val_json_file: "../data/snare/amt/processed_json/processed_val.json"
  test_json_file: "../data/snare/amt/processed_json/good_annotated_test.json"
  voxel_root_dir: '../data/snare/solid_64' # 128
  img_root_dir: "../data/snare/shapenet-sem/screenshots"
  image_size: 128
  voxel_size: 64


loss:
  type: ntxent # ntxent, triplet 
  ntxent:
    temperature: 0.1
    use_cosine_similarity: True
    alpha_weight: 0.25
  triplet:
    margin: 0.025
  

